<?php

$_products = array(
					'home'			=> array(
											'Total Security Suite with Cloud Security' 		=> '/home/total',
											'Internet Security Suite with Cloud Security'	=> '/home/internet',
											'Anti-Virus with Cloud Security'				=> '/home/antivirus'
											),
					'smb'			=> array(
											'ISS with Cloud Security for SMB'				=> '/smb/internet',
											'AV with Cloud Security for SMB'				=> '/smb/antivirus'
											),
					'enterprise'	=> array(
						    				'Enterprise with Cloud Security'				=> '/enterprise/enterprise',
						    				'Corporate with Cloud Security'					=> '/enterprise/corporate'
						    				)
				);

$_features = array(
			    	'' => array(
			    		'Proactive Security'						=> array('home' => array(1,1,1), 'smb' => array(1,1), 'enterprise' => array(1,1) ),
			    		'Real-time AV Scanning'						=> array('home' => array(1,1,1), 'smb' => array(1,1), 'enterprise' => array(1,1) ),
			    		'Winsock Layer Protection'					=> array('home' => array(1,1,1), 'smb' => array(1,1), 'enterprise' => array(1,1) ),
			    		'Advanced Proactive Detection'				=> array('home' => array(1,1,1), 'smb' => array(1,1), 'enterprise' => array(1,1) ),
			    		'Spyware, KeyLogger, Rootkit Blocker'		=> array('home' => array(1,1,1), 'smb' => array(1,1), 'enterprise' => array(1,1) ),
			    		'Real-Time File Monitor'					=> array('home' => array(1,1,1), 'smb' => array(1,1), 'enterprise' => array(1,1) ),
			    		'On-Demand Scan'							=> array('home' => array(1,1,1), 'smb' => array(1,1), 'enterprise' => array(1,1) ),
			    		'Anti-Spam (NILP, RBL, SURBL)'				=> array('home' => array(1,1,1), 'smb' => array(1,1), 'enterprise' => array(1,1) ),
			    		'Two Way Firewall'							=> array('home' => array(1,1,1), 'smb' => array(1,1), 'enterprise' => array(1,1) ),
			    		'Mail Anti-Phishing'						=> array('home' => array(1,1,1), 'smb' => array(1,1), 'enterprise' => array(1,1) ),
			    		'Malware URL Filter'						=> array('home' => array(1,1,1), 'smb' => array(1,1), 'enterprise' => array(1,1) ),
			    		'Web Safe'									=> array('home' => array(1,0,0), 'smb' => array(0,0), 'enterprise' => array(0,0) ),
			    		'Safe mode boot protection'					=> array('home' => array(1,1,1), 'smb' => array(1,1), 'enterprise' => array(1,1) ),
			    		'Rescure Mode'								=> array('home' => array(1,1,1), 'smb' => array(1,1), 'enterprise' => array(1,1) ),
			    		'Cloud security network'					=> array('home' => array(1,1,1), 'smb' => array(1,1), 'enterprise' => array(1,1) ),
			    		'USB Vaccination'							=> array('home' => array(1,1,1), 'smb' => array(1,1), 'enterprise' => array(1,1) ),
			    		'Sample Upload'								=> array('home' => array(1,1,1), 'smb' => array(1,1), 'enterprise' => array(1,1) ),
			    		'Web Protection'							=> array('home' => array(1,1,0), 'smb' => array(1,0), 'enterprise' => array(1,1) ),
			    		'Web Anti-Phishing'							=> array('home' => array(1,1,0), 'smb' => array(1,0), 'enterprise' => array(1,1) ),
			    		'Registry Cleaner'							=> array('home' => array(0,0,0), 'smb' => array(0,0), 'enterprise' => array(0,0) ),
			    		'Disk Defragmenter'							=> array('home' => array(0,0,0), 'smb' => array(0,0), 'enterprise' => array(0,0) ),
			    		'Import &amp; Export Security Settings'		=> array('home' => array(0,0,0), 'smb' => array(0,0), 'enterprise' => array(0,0) ),
			    		'Identity Protection'						=> array('home' => array(0,0,0), 'smb' => array(0,0), 'enterprise' => array(0,0) ),
			    		'Privacy Protection with Pop-Up Blocking'	=> array('home' => array(1,1,0), 'smb' => array(1,0), 'enterprise' => array(1,1) ),
			    		),
					'Endpoint Security'	=> array(
						'Device Control'							=> array('home' => array(1,1,0), 'smb' => array(1,0), 'enterprise' => array(1,1) ),
						'USB Blocking with Password Management'		=> array('home' => array(1,1,0), 'smb' => array(1,0), 'enterprise' => array(1,1) ),
						'Blocking of AutoPlay of USB Devices'		=> array('home' => array(1,1,0), 'smb' => array(1,0), 'enterprise' => array(1,1) ),
						'Recording of Files Copied to USB'			=> array('home' => array(1,0,0), 'smb' => array(1,0), 'enterprise' => array(1,1) ),
						'Blocking of CD/DVD'						=> array('home' => array(1,1,0), 'smb' => array(1,0), 'enterprise' => array(1,1) ),
						'Disabling of Webcam'						=> array('home' => array(1,1,0), 'smb' => array(1,0), 'enterprise' => array(1,1) ),
						'Disabling of SD Cards'						=> array('home' => array(1,1,0), 'smb' => array(1,0), 'enterprise' => array(1,1) ),
						'Read-Only USB'								=> array('home' => array(1,1,0), 'smb' => array(1,0), 'enterprise' => array(1,1) ),
						'USB Whitelisting/Scanning'					=> array('home' => array(1,1,0), 'smb' => array(1,0), 'enterprise' => array(1,1) ),
						'Bluetooth Control'							=> array('home' => array(0,0,0), 'smb' => array(0,0), 'enterprise' => array(1,1) ),
						'Proxy Setting Protection'					=> array('home' => array(0,0,0), 'smb' => array(0,0), 'enterprise' => array(1,1) ),
						'IP Protection'								=> array('home' => array(0,0,0), 'smb' => array(0,0), 'enterprise' => array(1,1) ),
						'Update Agent'								=> array('home' => array(0,0,0), 'smb' => array(0,0), 'enterprise' => array(1,1) ),
						'File Access Rights'						=> array('home' => array(0,0,0), 'smb' => array(0,0), 'enterprise' => array(1,1) ),
						'File Modification Prevention'				=> array('home' => array(0,0,0), 'smb' => array(0,0), 'enterprise' => array(1,1) ),
						'Secure Delete'								=> array('home' => array(1,1,0), 'smb' => array(1,0), 'enterprise' => array(1,1) ),
						'Application Control'						=> array('home' => array(1,1,0), 'smb' => array(1,0), 'enterprise' => array(1,1) ),
						'User Based Time Restriction'				=> array('home' => array(1,1,0), 'smb' => array(1,0), 'enterprise' => array(1,1) ),
						'Grid-based Web Access Timing'				=> array('home' => array(1,1,1), 'smb' => array(1,1), 'enterprise' => array(1,1) ),
						'History/Reports'							=> array('home' => array(1,1,1), 'smb' => array(1,1), 'enterprise' => array(1,1) ),
						'Web-based Help'							=> array('home' => array(1,1,1), 'smb' => array(1,1), 'enterprise' => array(1,1) ),
						'Safe Mode Boot Protection'					=> array('home' => array(1,1,1), 'smb' => array(1,1), 'enterprise' => array(1,1) ),
						'One Time Password'							=> array('home' => array(0,0,0), 'smb' => array(1,1), 'enterprise' => array(1,1) ),
						'Event Caching for Offline Endpoints'		=> array('home' => array(0,0,0), 'smb' => array(1,1), 'enterprise' => array(1,1) ),
						'Computer Discovery'						=> array('home' => array(0,0,0), 'smb' => array(1,1), 'enterprise' => array(1,1) ),
						'Network Monitoring tool'					=> array('home' => array(1,1,1), 'smb' => array(1,1), 'enterprise' => array(1,1) ),
						'Auto Update Rollback'						=> array('home' => array(1,1,1), 'smb' => array(1,1), 'enterprise' => array(1,1) ),
						'Hotfix Rollback'							=> array('home' => array(1,1,1), 'smb' => array(1,1), 'enterprise' => array(1,1) ),
						'Auto Download/Update Software Version'		=> array('home' => array(1,1,1), 'smb' => array(1,1), 'enterprise' => array(1,1) ),
						'Auto Backup / Restore of System Files'		=> array('home' => array(1,1,1), 'smb' => array(1,1), 'enterprise' => array(1,1) ),
						'Remote Support Application'				=> array('home' => array(1,1,1), 'smb' => array(1,1), 'enterprise' => array(1,1) ),
						'Virtual Keyboard'							=> array('home' => array(1,1,1), 'smb' => array(1,1), 'enterprise' => array(1,1) ),
						'Silent Mode'								=> array('home' => array(1,1,1), 'smb' => array(1,1), 'enterprise' => array(1,1) ),
						'User Defined File & Folder Protection'		=> array('home' => array(1,1,1), 'smb' => array(1,1), 'enterprise' => array(1,1) ),
						'Creating/Burning Bootable Rescue CD'		=> array('home' => array(1,1,1), 'smb' => array(1,1), 'enterprise' => array(1,1) ),
						'Automatic Patching of Windows&reg; Operating System Vulnerabilities'		=> array('home' => array(1,1,1), 'smb' => array(1,1), 'enterprise' => array(1,1) ),
						'Laptop Battery Power Saving Mode for Schedule Scan'						=> array('home' => array(1,1,1), 'smb' => array(1,1), 'enterprise' => array(1,1) ),
						'Advanced Self-Protection Feature'			=> array('home' => array(1,1,1), 'smb' => array(1,1), 'enterprise' => array(1,1) ),
						'Registry Monitoring'						=> array('home' => array(1,1,1), 'smb' => array(1,1), 'enterprise' => array(1,1) ),
						'Real-Time eMail Scan'						=> array('home' => array(1,1,1), 'smb' => array(1,1), 'enterprise' => array(1,1) ),
						'Password Protection'						=> array('home' => array(1,1,1), 'smb' => array(1,1), 'enterprise' => array(1,1) ),
						'Heuristic Scanning'						=> array('home' => array(1,1,1), 'smb' => array(1,1), 'enterprise' => array(1,1) ),
						'Personalized Dashboard'					=> array('home' => array(0,0,0), 'smb' => array(1,1), 'enterprise' => array(1,1) ),
						'Pulse/Push Updates'						=> array('home' => array(1,1,1), 'smb' => array(1,1), 'enterprise' => array(1,1) ),
						'SNMP Trap Management'						=> array('home' => array(0,0,0), 'smb' => array(0,0), 'enterprise' => array(1,1) ),
						'NAC & NAP Support'							=> array('home' => array(0,0,0), 'smb' => array(1,1), 'enterprise' => array(1,1) ),
						'SYSLOG Event Management'					=> array('home' => array(0,0,0), 'smb' => array(0,0), 'enterprise' => array(1,1) ),
						'Role Based Privilege for EMC'				=> array('home' => array(0,0,0), 'smb' => array(0,0), 'enterprise' => array(1,1) ),
						'ADS Integration'							=> array('home' => array(0,0,0), 'smb' => array(1,1), 'enterprise' => array(1,1) ),
						'VMWare Support'							=> array('home' => array(1,1,1), 'smb' => array(1,1), 'enterprise' => array(1,1) ),
						'On the fly language switch'				=> array('home' => array(1,1,1), 'smb' => array(0,0), 'enterprise' => array(0,0) ),
						'MailScan for Mail Servers'					=> array('home' => array(0,0,0), 'smb' => array(0,0), 'enterprise' => array(1,0) ),
						'Registration/Activation: (via Web Mail)'	=> array('home' => array(1,1,1), 'smb' => array(1,1), 'enterprise' => array(1,1) ),
						),
					'Management Console' => array(
						'Secure Web Based Management Console (SSL)'				=> array('home' => array(0,0,0), 'smb' => array(1,1), 'enterprise' => array(1,1) ),
						'Remote Installation of Clients'						=> array('home' => array(0,0,0), 'smb' => array(1,1), 'enterprise' => array(1,1) ),
						'Remote Installation of Third Party Software'			=> array('home' => array(0,0,0), 'smb' => array(1,1), 'enterprise' => array(1,1) ),
						'Automated Uninstallation of Known Antivirus Software'	=> array('home' => array(0,0,0), 'smb' => array(1,1), 'enterprise' => array(1,1) ),
						'Centralized Reporting Feature'							=> array('home' => array(0,0,0), 'smb' => array(1,1), 'enterprise' => array(1,1) ),
						'Top Ten Summary Reports'								=> array('home' => array(0,0,0), 'smb' => array(1,1), 'enterprise' => array(1,1) ),
						'Email Based Event Alerts'								=> array('home' => array(0,0,0), 'smb' => array(1,1), 'enterprise' => array(1,1) ),
						'Detailed System Information of all Clients on Console (Asset Management)'	=> array('home' => array(0,0,0), 'smb' => array(1,1), 'enterprise' => array(1,1) ),
						'Hardware/Software Installation/Uninstallation Events'	=> array('home' => array(0,0,0), 'smb' => array(1,1), 'enterprise' => array(1,1) ),
						'Document Printing Events'								=> array('home' => array(0,0,0), 'smb' => array(1,1), 'enterprise' => array(1,1) ),
						'Client Live Updater'									=> array('home' => array(0,0,0), 'smb' => array(1,1), 'enterprise' => array(1,1) ),
						)
			    	);