<main>
    <div class="container">
	    <div class="row">
		    <!-- Sidebar -->
		    <div class="col-sm-3 sidebar">
		    	<p><a href="/products">Products Home <i class="fa fa-sort-desc fa-rotate-270"></i></a></p>
		    </div>
		    <!-- /Sidebar -->

		    <!-- Content -->
		    <div class="col-sm-9">
			    

			    <div class="row">
				    <div class="col-sm-4">
					    <!-- Image -->
					    <img src="/assets/img/mailscan/mailscan-boxshot.png" class="img-responsive">
				    </div>

				    <div class="col-sm-8">
				    	<h1 class="page-header">Mailscan<br />Virus Protection <span>and</span> Internet Security Solutions</h1>

					    <p>MailScan is the advanced Real-time AntiVirus and AntiSpam solution for Mail Servers. MailScan protects organizations network against Virus, Worm, Trojan and many other information security threats. Employing an array of intelligent filters, MailScan offers powerful protection against Spam and Phishing mails along with comprehensive content security.</p>

						<?php
						$group = 'mailscan';
						$key = 'mailscan';
						include 'site/products/_price_widget.php' ?>
				    </div>
			    </div>

			    <hr />

			    <div class="row feature-container">
			    	<?php
				    $_features = array(
						array(
				    		'icon'			=> 'fa-cloud',
				    		'title'			=> 'Web Based Administration',
				    		'description'	=> "MailScan Administration Console can be accessed using a browser, thus enabling Remote Administration of the application."
				    		),
						array(
				    		'icon'			=> 'fa-clock-o',
				    		'title'			=> 'Real-Time Virus Scanning at the Mail Gateway',
				    		'description'	=> "Scans emails for all types of Virus and other Malware in Real-Time including all inbound and outbound Mail Traffic."
				    		),
						array(
				    		'icon'			=> 'fa-paperclip',
				    		'title'			=> 'Attachment Filtering',
				    		'description'	=> "Extensive options to block certain attachments like EXE, COM, CHM or BAT from being sent or received."
				    		),
						array(
				    		'icon'			=> 'fa-file-text-o',
				    		'title'			=> 'Real-Time Content Scanning',
				    		'description'	=> "All incoming and outgoing messages are scanned in Real-Time for offensive words and Adult Content, with the help of Security Policies."
				    		),
						array(
				    		'icon'			=> 'fa-cogs',
				    		'title'			=> 'Advanced AntiSpam and AntiPhishing',
				    		'description'	=> "Using a combination of technologies like Real-time Black List, SURBL Checking, MX/A DNS Record Verification, Reverse DNS, X-Spam Rules Check, Sender Policy Framework and Non Intrusive Learning Patterns spam and phishing emails are blocked."
				    		),
						array(
				    		'icon'			=> 'fa-cubes',
				    		'title'			=> 'Non-Intrusive Learning Patterns (NILP)',
				    		'description'	=> "NILP is a revolutionary technology from MicroWorld that works on the principles of Artificial Intelligence, which employs an adaptive mechanism in Spam and Phishing Control."
				    		),
						array(
				    		'icon'			=> 'fa-check',
				    		'title'			=> 'Autogenerated Spam Whitelist',
				    		'description'	=> "When a local user sends a mail to an email address, the system automatically adds that ID to the Spam Whitelist."
				    		),
						array(
				    		'icon'			=> 'fa-envelope-o',
				    		'title'			=> 'LDAP & POP3 Authentication',
				    		'description'	=> "Supports LDAP & POP3 Authenticated Web Administration."
				    		),
						array(
				    		'icon'			=> 'fa-archive',
				    		'title'			=> 'Comprehensive Attachment & eMail Archiving',
				    		'description'	=> "Customizable options to archive e-mails and attachments flowing in and out of the system. This feature also helps in comprehensive Content Auditing."
				    		),
						array(
				    		'icon'			=> 'fa-refresh',
				    		'title'			=> 'Automated Hourly Updates',
				    		'description'	=> "The antivirus and spam databases are automatically updated every hour for instant protection from emerging threats."
				    		),
						array(
				    		'icon'			=> 'fa-bullhorn',
				    		'title'			=> 'Virus Outbreak Alerts',
				    		'description'	=> "A Virus Outbreak Alert is sent to the administrator providing a detailed report of virus emails received within a defined span of time."
				    		),
						array(
				    		'icon'			=> 'fa-ban',
				    		'title'			=> 'Relay Control',
				    		'description'	=> "Stops spammers from using your organization's IP addresses to send spam."
				    		),
						array(
				    		'icon'			=> 'fa-certificate',
				    		'title'			=> 'Customized Disclaimers',
				    		'description'	=> "Easy to use options to add customized Disclaimers to all external and internal emails."
				    		),
						array(
				    		'icon'			=> 'fa-bar-chart-o',
				    		'title'			=> 'Extensive Reports',
				    		'description'	=> "Provides advanced analytical reports in graphical and Non-graphical formats."
				    		)

				    	);
					
					foreach($_features as $_f) { ?>
					<div class="media feature col-sm-10 col-sm-offset-1">
						<a class="icon">
							<i class="fa <?= $_f['icon'] ?> fa-fw"></i>
						</a>
						
						<div class="media-body">
					    	<h4 class="media-heading"><?= $_f['title'] ?></h4>
					    	
					    	<p><?= nl2br($_f['description']) ?></p>
				    		
					  	</div>
					</div>

					<?php } ?>
					
			    </div>
		    </div>
		    <!-- /Content -->
	    </div>
	</div>


</main>